### PR TITLE
Include SQL class only if necessary

### PR DESCRIPTION
**Pull request by jacksgt**
required when both vision_intranet and vision_webshop modules
container sql databases

### CODE REVIEW

**Review by martialblog — COMMENTED** [review]
> require  => Class['::vision_mysql::server']

Not sure what happens if the class :vision_mysql::server isn't included... Cause now it seems optional.

**Comment by jacksgt** [comment]
> Not sure what happens if the class :vision_mysql::server isn't included... Cause now it seems optional.

At least in our case, at least `vision_webshop` OR `vision_intranet` is always included. Though I can see what you mean. I guess the resource will simply fail if the requirement can't be met, which sounds reasonable.

**Comment by jacksgt** [comment]
Anyway, I did some testing in Vagrant and it works fine with any of these combinations:
* `vision_webshop` AND `vision_intranet`
* ONLY `vision_webshop`
* ONLY  `vision_intranet`

I concur that the logic coupling is not pretty, but I don't see any other way of solving this.

**Comment by martialblog** [comment]
:+1:

**Pull request merged**
